version: "3.8"
services:
  redis:
    image: redis:8.0.2
    container_name: redis
    ports:
      - "6379:6379"

  bongbaek-server:
    image: ${DOCKER_USERNAME}/bongbaek-server:latest
    container_name: bongbaek-server
    ports:
      - "8080:8080"
    depends_on:
      - redis

  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8888:8080"
    environment:
      DOZZLE_USERNAME: ${DOZZLE_USERNAME}
      DOZZLE_PASSWORD: ${DOZZLE_PASSWORD}
    restart: always
