events {}

http { # 이후 JWT 캐싱을 위해 L7 통신 사용
    upstream bongbaek_server {
        least_conn;
        server bongbaek1:8080;
        server bongbaek2:8080;
    }

    server {
        listen 80;
        server_name _;

        location / {
            proxy_pass http://bongbaek_server;

            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header Host $host;

            # 실패 시 다른 upstream으로 재시도
            proxy_next_upstream error timeout http_502 http_503 http_504;
            proxy_connect_timeout 10s;   # 연결 시도 제한 시간
            proxy_read_timeout 10s;     # 응답 대기 시간
        }

        location /stub_status {
            stub_status;
            allow 127.0.0.1;
            allow 172.0.0.0/16;   # 도커 브리지 네트워크 대역
            deny all;
        }
    }
}
