events {}

http { # 이후 JWT 캐싱을 위해 L7 통신 사용
    upstream bongbaek_server {
        least_conn;
        server blue:8080;
        server green:8080;
    }

    server {
        listen 80;
        server_name _;

        location / {
            proxy_pass http://bongbaek_server;

            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header Host $host;
        }
    }
}
